export const cardList = [
  {
    id: 1,
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "БЕЗ СТАТУСА", 
  },
  {
    id: 2,
    topic: "Research",
    title: "Новая задача",
    date: "25.11.23",
    status: "НУЖНО СДЕЛАТЬ",
  },
  {
    id: 3,
    topic: "Copywriting",
    title: "Написать статью о React",
    date: "15.12.23",
    status: "В РАБОТЕ", 
  },
  {
    id: 4,
    topic: "Web Design",
    title: "Адаптивная верстка",
    date: "01.01.24",
    status: "ТЕСТИРОВАНИЕ", 
  },
  {
    id: 5,
    topic: "Research",
    title: "Изучить хуки в React",
    date: "10.01.24",
    status: "ГОТОВО",
  },
  {
    id: 6,
    topic: "Copywriting",
    title: "Создать тексты для баннеров",
    date: "05.11.23",
    status: "БЕЗ СТАТУСА",
  },
  {
    id: 7,
    topic: "Web Design",
    title: "Дизайн главной страницы",
    date: "20.10.23",
    status: "БЕЗ СТАТУСА",
  },
  {
    id: 8,
    topic: "Copywriting",
    title: "Написать статью о Vue",
    date: "04.12.23",
    status: "ТЕСТИРОВАНИЕ", 
  },
  {
    id: 9,
    topic: "Research",
    title: "Изучить компоненты",
    date: "17.02.23",
    status: "В РАБОТЕ",
  },
];
